name: mlops_workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.1=openblas
  - brotli-python=1.0.9=py311h6a678d5_7
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.3.11=h06a4308_0
  - cachecontrol=0.14.0=pyhd8ed1ab_0
  - cachecontrol-with-filecache=0.14.0=pyhd8ed1ab_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py311hb3a22ac_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - cleo=2.1.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - crashtest=0.4.1=pyhd8ed1ab_0
  - cryptography=42.0.5=py311h63ff55d_0
  - dbus=1.13.6=h5008d03_3
  - distlib=0.3.8=pyhd8ed1ab_0
  - dulwich=0.21.7=py311h459d7ec_0
  - expat=2.6.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - jaraco.classes=3.3.1=pyhd8ed1ab_0
  - jeepney=0.8.0=pyhd8ed1ab_0
  - keyring=24.3.1=py311h38be061_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libglib=2.78.4=hdc74915_0
  - libgomp=13.2.0=h807b86a_5
  - libiconv=1.17=hd590300_2
  - libopenblas=0.3.26=pthreads_h413a1c8_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - more-itertools=10.2.0=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - numpy=1.26.4=py311h24aa872_0
  - numpy-base=1.26.4=py311hbfb1bba_0
  - openblas=0.3.26=pthreads_h7a3da1a_0
  - openssl=3.2.1=hd590300_1
  - pcre2=10.42=hebb0a14_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pip=23.3.1=py311h06a4308_0
  - pkginfo=1.10.0=pyhd8ed1ab_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - poetry=1.8.2=linux_pyha804496_0
  - poetry-core=1.9.0=pyhd8ed1ab_0
  - poetry-plugin-export=1.7.1=pyhd8ed1ab_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyproject_hooks=1.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.7=h955ad1f_0
  - python-build=1.1.1=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-installer=0.7.0=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_0
  - secretstorage=3.3.3=py311h38be061_2
  - shellingham=1.5.4=pyhd8ed1ab_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.12.4=pyha770c72_0
  - trove-classifiers=2024.3.25=pyhd8ed1ab_0
  - virtualenv=20.25.1=pyhd8ed1ab_0
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - aiohttp==3.9.3
      - aiohttp-cors==0.7.0
      - aiorwlock==1.4.0
      - aiosignal==1.3.1
      - alembic==1.13.1
      - altair==4.2.2
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - blessed==1.20.0
      - blinker==1.7.0
      - boto3==1.34.62
      - botocore==1.34.62
      - cachetools==5.3.3
      - category-encoders==2.6.3
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorful==0.5.6
      - colorlog==6.8.2
      - comm==0.2.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - databricks-cli==0.18.0
      - debugpy==1.8.1
      - decorator==5.1.1
      - deepchecks==0.18.1
      - defusedxml==0.7.1
      - docker==6.1.3
      - dogpile-cache==1.3.2
      - entrypoints==0.4
      - executing==2.0.1
      - fastapi==0.95.2
      - filelock==3.13.1
      - flask==3.0.2
      - fonttools==4.49.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - google-api-core==2.17.1
      - google-auth==2.28.2
      - googleapis-common-protos==1.63.0
      - gpustat==1.1.1
      - great-expectations==0.18.3
      - greenlet==3.0.3
      - grpcio==1.62.1
      - gunicorn==21.2.0
      - h11==0.14.0
      - httpcore==1.0.4
      - httptools==0.6.1
      - httpx==0.26.0
      - importlib-metadata==6.11.0
      - iniconfig==2.0.0
      - ipykernel==6.29.3
      - ipython==8.22.2
      - ipython-genutils==0.2.0
      - ipywidgets==7.8.1
      - iso8601==2.1.0
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - jinja2==3.1.3
      - jmespath==1.0.1
      - joblib==1.3.2
      - json5==0.9.22
      - jsonpatch==1.33
      - jsonpickle==3.0.3
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - jupyter-events==0.9.1
      - jupyter-lsp==2.2.4
      - jupyter-server==2.13.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.4
      - jupyterlab-widgets==1.1.7
      - keystoneauth1==5.6.0
      - kiwisolver==1.4.5
      - lightgbm==4.0.0
      - makefun==1.15.2
      - mako==1.3.2
      - markdown==3.5.2
      - markupsafe==2.1.5
      - marshmallow==3.21.1
      - matplotlib==3.8.3
      - matplotlib-inline==0.1.6
      - minio==7.1.3
      - mistune==3.0.2
      - mlflow==2.9.2
      - msgpack==1.0.8
      - multidict==6.0.5
      - nbclient==0.10.0
      - nbconvert==7.16.2
      - nbformat==5.10.2
      - nbgrader==0.9.1
      - nest-asyncio==1.6.0
      - netifaces==0.11.0
      - notebook==7.1.1
      - notebook-shim==0.2.4
      - nvidia-ml-py==12.535.133
      - oauthlib==3.2.2
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - openstacksdk==2.1.0
      - optuna==3.5.0
      - os-service-types==1.7.0
      - overrides==7.7.0
      - packaging==23.2
      - pandas==2.1.4
      - pandocfilters==1.5.1
      - parso==0.8.3
      - patsy==0.5.6
      - pbr==6.0.0
      - pillow==10.2.0
      - plotly==5.20.0
      - pluggy==1.4.0
      - prometheus-client==0.13.1
      - prompt-toolkit==3.0.43
      - protobuf==3.20.3
      - psutil==5.9.8
      - psycopg2-binary==2.9.9
      - pure-eval==0.2.2
      - py-spy==0.3.14
      - pyarrow==14.0.2
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pydantic==1.10.14
      - pygments==2.17.2
      - pyjwt==2.8.0
      - pynomaly==0.3.3
      - pyparsing==3.1.2
      - pytest==8.1.1
      - pytest-timeout==2.3.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - python-utils==3.8.2
      - pytz==2023.4
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - querystring-parser==1.2.4
      - rapidfuzz==3.6.2
      - ray==2.9.3
      - referencing==0.33.0
      - requestsexceptions==1.4.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.0
      - rsa==4.9
      - ruamel-yaml==0.17.17
      - s3transfer==0.10.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - send2trash==1.8.2
      - setuptools==69.2.0
      - six==1.16.0
      - smart-open==7.0.1
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - sqlalchemy==1.4.51
      - sqlparse==0.4.4
      - stack-data==0.6.3
      - starlette==0.27.0
      - statsmodels==0.14.1
      - stevedore==5.2.0
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tensorboardx==2.6.2.2
      - terminado==0.18.1
      - thefuzz==0.20.0
      - threadpoolctl==3.3.0
      - tinycss2==1.2.1
      - toolz==0.12.1
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.2
      - types-python-dateutil==2.8.19.20240311
      - typing-extensions==4.10.0
      - tzdata==2024.1
      - tzlocal==5.2
      - uri-template==1.3.0
      - urllib3==2.0.7
      - uvicorn==0.19.0
      - uvloop==0.19.0
      - watchfiles==0.21.0
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - websockets==12.0
      - werkzeug==3.0.1
      - widgetsnbextension==3.6.6
      - wrapt==1.16.0
      - xgboost==2.0.3
      - yarl==1.9.4
      - zipp==3.18.0
